### ISSUE TITLE
Styling the lists

### ISSUE THREAD

**Issue by vbaimas** [WordPress/twentytwenty#215]
I add some widgets in the footer and the style in the lists does not apply.

<img width="1238" alt="style-the-lists" src="https://user-images.githubusercontent.com/5068068/64677557-79731b80-d480-11e9-94e7-be4d5a2ef742.png">

**Comment by acosmin** [comment]
Isn't that the way they should look?

**Comment by vbaimas** [comment]
@acosmin we should styling lists, like to remove the bullets.. 
Sorry, I didn't explain it in my first comment.

**Comment by nielslange** [comment]
@vbaimas Do you mean that list items should not have bullet points?

**Comment by nielslange** [comment]
@vbaimas I believe due to usability reasons, lists should have bullet points to be identifiable as lists. 

cc: @afercia

**Comment by afercia** [comment]
@nielslange thanks for the ping!.

**Visually**
I'd tend to think this is a case similar to the "[should links be always underlined](https://make.wordpress.org/core/handbook/best-practices/coding-standards/accessibility-coding-standards/#links-underline-or-no-underline)" issue :) Links within lines or blocks of text should always be underlined. When links can be identified as such by the context, for example because they’re part of a menu, or a set of links clearly identified as user interface controls, they don’t necessarily need to be underlined.

Similarly for lists: I'd say in the case of widgets the context clarifies they're lists. However, lists within the post content should keep the native styling with bullets/numbers/etc.

**Semantically (non-visually)**
As long as they use proper markup (`<ul>` and `<ol>`) they convey the correct information. However, [Safari removes the native semantics when lists are styled](https://codepen.io/afercia/full/WxmJWx) thus VoiceOver doesn't announce styled lists as lists. This is a known issue that Apple isn't going to fix because they consider it a "feature" that helps their screen reader users by reducing "noise".

Can be fixed by adding a `role="list"` attribute (which is redundant) or with some CSS tricks: more details:

**"Fixing" Lists**
by Scott O'Hara
https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html

I'd totally leave this to a design choice. If the preferred option is to use `list-style: none`, it would be nice to:
- either consider to add the `role="list"` to all the lists generated by WP core
- or try the CSS fix with `list-style: url(...)` suggested in the post linked above

**Comment by pattonwebz** [comment]
We talked about this one a bit today and decided that better styling may be in order for lists inside widgets. We will keep the bullets for the moment but will revisit this in the near future after some adjustments.

**Comment by karmatosed** [comment]
I actually like the bullets, just as a little point. It makes them obviously lists to me not a collection of links.

**Comment by nielslange** [comment]
Guess we all agree that lists should be styled like lists, thus, I'm going to close this issue for now.
