### ISSUE TITLE
Instant live preview of color customization

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentytwenty#285]
Instant live preview of color customizations in the customizer can be a great experience and help users quickly select just the right colors for their site. There are several potential implementation approaches. Ideally, the solution will:
1. Instantly preview most of the colors in JS.
2. Not duplicate any CSS logic in PHP and JS.
3. Not duplicate color calculation logic in PHP and JS.
4. Ensure that previewed color CSS exactly matches what's shown on the frontend.

### Proposal
I am proposing a general strategy rather than an actual PR so that we can make decisions about the approach before building an implementation following decisions on #284.

Starting with item 4, the current approach performs a full page refresh in the customize preview to preview colors and match the frontend. We can refine this behavior by leveraging selective refresh, only reloading the relevant `style` element from PHP. Conceptually, this is done with:

```
$wp_customize->selective_refresh->add_partial( 'twentytwenty_colors', array(
	'selector'        => '#twentytwenty-colors', // <style> element
	'settings'        => array( 'background_color', 'accent_color' ),
	'render_callback' => 'twentytwenty_color_css_frontend',
) );
```
To implement item 1 while observing 2 and 3, we need to creatively consider ways to update some of the colors without duplicating logic, knowing that the full CSS will be rebuilt with color calculations in PHP periodically. I've found that doing a find/replace for the customize color within the generated CSS works well for this purpose. 

This starts with adding the color setting values as `data-` attributed to the `<style>` element if `is_customize_preview()`. Then, our settings are set to `transport => postMessage`. Finally, in the enqueued customize preview JS file, we can use something like this for each color setting:

```
wp.customize( 'accent_color', function( value ) {
	value.bind( function( to ) {
		// Update custom color CSS
		var style = $( '#twentytwenty-color' ),
		      color = style.data( 'accent-color' ),
		      css = style.html();
		css = css.split( color ).join( to ); // equivalent to css.replaceAll.
		style.html( css )
		       .data( 'color', to );
	} );
} );
```

Does anyone have alternative approaches to consider for discussion?

**Comment by joyously** [comment]
CSS Custom Properties

**Comment by aristath** [comment]
While I agree that duplicating logic in PHP & JS is sub-optimal, using partial-refreshes won't be less code, and the result won't be instant in the customizer, there will be delays.

Alternative approaches:

* Instead of calculating things in PHP we could do it in JS, and the same script could be used both in the customizer for `postMessage` and on the frontend of the site. But that would mean that if client has no JS, colors won't be right (we do accomodate no-JS in twentytwenty, don't we?).
* When the value of the colorpicker changes for some settings in the customizer, we could save the value as an array instead of a string. That array can contain things like `hex`, `hue`, `saturation`, `lightness`, `luminosity`, `readable-text`, `dark`, `light` or whatever we want. Some things are already available from the `Color` class which is available in the customizer when enqueueing colorpickers, so the code required would be minimal. This way all calculations are on the JS side and we just pick what we want to use from the theme_mod.
* When the value of the colorpicker changes, save an extra `theme_mod` with the data we want. Again this can all be done in JS and won't require a lot of code, it's easy to accomplish. That extra theme_mod would be control-less, so basically just init a new setting from the customizer API and save the value we need there. It can then be used in PHP using `get_theme_mod` as usual, and in the customizer things would just work with postMessage.

While I love CSS custom-properties and use them everywhere, I don't see how they would help us calculate light/dark colors and achieve better a11y. Additionally they are not compatible with IE11 - which WP-Core still supports. It would be fine in any other theme but not a core theme. We'd have to include a polyfill, and while there are a few out there none of them work correctly - so we'd probably have to write a custom polyfill.

**Comment by celloexpressions** [comment]
For reference here is a link to a (15MB .gif) [screencast of a theme that uses JS for color-swapping and PHP with selective refresh to maintain contrast](https://celloexpressions.com/wp-content/uploads/2019/09/linework-instant-color-live-preview.gif), as I proposed. There is a delay in the preview if you make a significant change to the relative brightness of the color. I do think that this can be implemented with less code than duplication, or a similar amount to doing most of the logic in JS.

Here are my thoughts on the alternative options above:
1. For this option we could run the CSS-generating JS in the customize-controls frame, passing the generated CSS into the customize preview with postMessage and back to the server as its own setting. That setting gets cached and printed to the `style` tag on the frontend, similar to what we would do if the logic is in PHP. The color calculations only run when they're being customized, and the results are cached for frontend output.
2. This is a good idea, although it would require changes in core. We did add the hue-slider mode to the color picker in core for Twenty Seventeen, although the timing was difficult and we had been able to use a `range` control with the custom color feature fully functional in the meantime. I worry that going in this direction would risk custom colors needing to be pulled out of the theme and into a plugin that has more time for development, as happened with Twenty Fourteen.
3. This would also ideally be closer to a mechanism in core, but seems slightly more appropriate to live in the theme since it's a separate setting (for each user-selected color?). Similar to what we're discussing in 1.
4. Agreed that CSS custom-properties probably aren't the answer for this theme, although it seems like this could be feasible in the next bundled theme.

**Comment by joyously** [comment]
With the latest master, there is a problem with the background color. This screenshot was taken after dragging the color picker around, then changing the Accent color, and dragging the background color around again. Note that the swatch and preview show a saturated color, but the control is set to very little saturation.

![Customizer-color-wrong](https://user-images.githubusercontent.com/7957680/65381347-e70b1d00-dcb4-11e9-87d9-5d51765aca1d.jpg)

**Comment by aristath** [comment]
That sounds more like an issue with the colorpicker itself, not the theme.

**Comment by joyously** [comment]
It seems like the accent color is feeding back into the background color somehow, so I thought it had to do with your calculations.

**Comment by ianbelanger79** [comment]
@celloexpressions and @aristath I am wondering if this issue can be closed out? Has everything mentioned here been addressed in already merged PR's? Please let me know, thanks

**Comment by aristath** [comment]
@ianbelanger79 I believe this one can be be closed, yes.
