### ISSUE TITLE
Adjust Drop Cap Screen Size Ratio

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#312]
Drop cap remains large on mobile screen

When viewing a post, the title adjusts to different screen size, so in comparison, the drop cap letter doesn't change much

### [mobile view]
![twentytwenty-drop-cap-mobile](https://user-images.githubusercontent.com/1679025/64994875-cc493a80-d8a7-11e9-84af-f217890121e7.png)

### [desktop view]
![twentytwenty-drop-cap-desktop](https://user-images.githubusercontent.com/1679025/64994878-ceab9480-d8a7-11e9-9c6a-6942869631c2.png)

**Comment by andersnoren** [comment]
@okpierre I've reduced the font size of the drop cap a bit in #328 – enough that it shouldn't cause an extra line-break for you (since the serif font stack uses system fonts, the line height differs somewhat). They still take up two lines on mobile, though – the drop cap becomes miniscule if it only takes up two.
