### ISSUE TITLE
Analyse impact of NonBreakingSpaceOverride font

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#347]
As @joyously pointed out in https://wordpress.slack.com/archives/C02RP4VMP/p1568817804266800 there might be an issue when the Twenty Twenty theme is using the NonBreakingSpaceOverride font and users are using the CSS unit `ch`. 

In https://github.com/WordPress/twentynineteen/commit/aeb424fbfd144fb2ff9b6c51a406030b935f8b2f @kjellr mentioned:

> Chrome renders extra-wide &nbsp; characters for the Hoefler Text font. 
> This results in a jumping cursor when typing in both the Classic and block 
> editors. The following font-face override fixes the issue by manually inserting 
> a custom font that includes just a Hoefler Text space replacement for that 
> character instead.

@andersnoren As we're not using the Hoefler Text font for Twenty Twenty can't we get rid of the NonBreakingSpaceOverride font?

**Comment by andersnoren** [comment]
@nielslange Hoefler Text is used for the `.entry-content`, `.comment-content` and `.widget-content`. I don't think this issue is worth removing the `NonBreakingSpaceOverride` fix over, given the spacing issues Hoefler Text has without it in some cases (https://github.com/WordPress/twentynineteen/issues/657). Finding a solution that includes fixes for both would be best, of course, but I'm not sure what's required for that. 

I think we would need to update the NonBreakingSpaceOverride font to include a zero glyph (since that's the glyph the `ch` unit gets its value from) that's close to the width of Hoefler Text and the rest of the fallback fonts, but that would result in a zero glpyh that doesn't match the rest of the font for some users.

**Comment by nielslange** [comment]
@andersnoren Thanks for your reply! Shall we skip this issue for now and address it later, once we're done with Beta 1? After all, it seems to be an edge case. What do you think?

**Comment by andersnoren** [comment]
@nielslange I think so. It feels like it could be a pretty deep rabbithole to go down before the beta.
