### ISSUE TITLE
Alignment of Navigation buttons isn't working as expected on mobile

### ISSUE THREAD

**Issue by MarkErik** [WordPress/twentytwenty#407]
Hi!
Really like the look of this theme. (Although I'm not a huge fan of the recent addition of the // centered on the bottom nav area).

I am using Wordpress 5.2.3 with LearnDash 3.0. Viewing on Safari on Desktop, and Safari Mobile (on iPhone 7 - iOS 12).

On desktop, there are nice nav links that appear near the bottom of the page to take the visitor to the next page. They are positioned/aligned on the right side to progress to the next page, and aligned to the left to go back. This makes a lot of sense. I've attached images (I'm using placeholder topics called "First Topic" and "Second Topic"

**Issue:**
On mobile, the navigation links are aligned to the left, regardless of if they are moving forward or back. This makes the mental model a bit more difficult to understand. 

**Expected behaviour:**
The link to go to the next page (in the attached example "second topic"), would be right aligned as on the desktop.

![IMG_1070](https://user-images.githubusercontent.com/23254168/65367005-fc089180-dc5d-11e9-9cbc-d48bc99c592a.png)
![IMG_1071](https://user-images.githubusercontent.com/23254168/65367006-fc089180-dc5d-11e9-88b5-8ef1eb28717b.png)
<img width="979" alt="Screenshot 2019-09-21 at 10 41 02 AM" src="https://user-images.githubusercontent.com/23254168/65367007-fc089180-dc5d-11e9-8f6c-3270225048d9.png">
<img width="1053" alt="Screenshot 2019-09-21 at 10 40 48 AM" src="https://user-images.githubusercontent.com/23254168/65367009-fca12800-dc5d-11e9-8a9f-39dde133f306.png">

**Comment by andersnoren** [comment]
@MarkErik Thanks for creating the issue! On mobile, due to the lack of horizontal space, both the next and previous links are aligned to the left, with the arrow to the left of them indicating whether respective post is the next or previous one.

This is how it looks when there are two posts displayed:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/8181091/65369766-957d7680-dc51-11e9-8c93-3638d2208bdc.png">

I agree that it could look a bit confusing when there's only one previous post. I don't think it's worth creating a mobile specific solution with a right-aligned link and arrow when there's only one previous post, though. It would require quite a bit of extra code and would make the pagination look inconsistent depending on whether its displaying both previous and next or only the previous link.

**Comment by MarkErik** [comment]
@andersnoren Thank you for the explanation. I feel silly for not considering the the case with a page before and after the current page, and how to handle that on mobile. I appreciate that you have the task of making this look great for as many possible use-cases within the broad WP community.

When I saw the very nice design of Twenty Twenty, I was hoping I could stick as close as possible to the base theme, and turn off the LearnDash UI elements.

Ultimately, I'm aiming for a strong visual indication of structure and progression for students going through the course I would like to design. So that they can quickly understand what was the previous topic, and what is the next one in sequence.

Thanks again for yours and everyones work on this!

**Comment by andersnoren** [comment]
@MarkErik No worries, and no apologies needed for creating an issue!

**Comment by MarkErik** [comment]
And if I understand correctly, something like:

<img width="361" alt="right align" src="https://user-images.githubusercontent.com/23254168/65370192-ad242180-dc88-11e9-975c-dd95ae3d9490.png">

is the case of requiring extra code for a mobile specific situation?
(where if there was only the "next" link it would be right-aligned)

**Comment by joyously** [comment]
^^ That would be my expectation also.

Don't forget that it should be reversed for RTL languages. (next on the left and previous on the right, plus the arrows)
