### ISSUE TITLE
Search icon + text better fitting with menu line.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#487]
Hey

The Search icon and Search text could fit better in with the menu line.
Right now it feels like it takes up too much space automatically making it more important then the menu links.

![Screen Shot 2019-09-24 at 08 11 55](https://user-images.githubusercontent.com/5323259/65485862-43339400-dea3-11e9-96f8-43d0ffa33cb2.png)

Adding different options. Working on having it harmonize better with the menu text links.

Moving the Search icon and text a little further up.
![Twenty-Twenty-search-up](https://user-images.githubusercontent.com/5323259/65486472-d4573a80-dea4-11e9-8799-1eecd54c2734.jpg)

Removing the Search text.
![Twenty-Twenty-Search-no-text](https://user-images.githubusercontent.com/5323259/65486509-ecc75500-dea4-11e9-9d66-856fdd5d5e34.jpg)

A smaller Search icon.
![Twenty-Twenty-Search-icon-smaller](https://user-images.githubusercontent.com/5323259/65486646-46c81a80-dea5-11e9-89b6-eee29ef1d748.jpg)

**Comment by andersnoren** [comment]
Hi @paaljoachim,

The icon labels were added for accessibility reasons, after a discussion in #93, so those need to remain.

Alignment of the icons gets tricky, since it's not just the search icon that needs to be aligned, but also the Expandable Menu icon, which is displayed when the "Expandable Menu" menu location has a menu set. Since the icons have different height, you can't center both the icon and the text of both buttons without either button feeling misaligned:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8181091/65575802-f0c0a900-df70-11e9-9477-b0da2d6e5ffc.png">

Because of that, I think aligning the header toggles so the icons are centered with the menu, and allowing the toggle text to be positioned beneath, is the better option.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8181091/65575860-0e8e0e00-df71-11e9-9eb9-e854d6b5b276.png">
