### ISSUE TITLE
HR color issues

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentytwenty#533]
The HR element is almost invisible when selecting certain background colors.

HR Element on front end - nearly invisible
![hr-front-end](https://user-images.githubusercontent.com/34601694/65618160-d47e3580-df8b-11e9-96a7-48861d389f5b.PNG)

HR Element in Customizer - with the same settings as the above picture
![hr-customize](https://user-images.githubusercontent.com/34601694/65618169-d811bc80-df8b-11e9-9da0-8450e7125176.PNG)

As you can see, the 2 do not match and the HR Element is nearly invisible

**Comment by andersnoren** [comment]
The hr element on the front-end is using the `border` a11y color currently – we could move it to the `secondary` color, to oomph it up. I can update #532 with that change.

It looks like the `border` a11y color needs to get more contrast against the background as well, though.

**Comment by nielslange** [comment]
@andersnoren Your PR https://github.com/WordPress/twentytwenty/pull/535 solved this issue so that it can be closed, right?

**Comment by andersnoren** [comment]
@nielslange Right, yes!

**Comment by aristath** [comment]
Apologies for commenting on an already closed issue, I just came across it and want to make sure we're OK.

@andersnoren 
> It looks like the border a11y color needs to get more contrast against the background as well, though.

Right now the calculations are done like this: https://github.com/WordPress/twentytwenty/blob/8fe0843fdd0544139486385c09bd34cc86434cb2/assets/js/customize-controls.js#L70-L75

So borders use the same hue as the background-color, the saturation is multiplied by `0.3922` to make it less intense, and for the lightness if the background is dark then I'm just adding 9, otherwise substract 9.
The above calculations were done like that to make the color exactly the same as we had it in `style.css` before the a11y implementation.

We can tweak those rules as much as we want, I was simply limited by the fact that i wanted the initial value to be identical to what we previously had.

**Comment by andersnoren** [comment]
No worries @aristath! I should have pinged you in my initial comment – sorry about that.

I think we might want to amp up the contrast a bit, even if that results in the colors not matching the ones used in the design. The color contrast for a border against a completely white background right now is 1.23, and the contrast for a border against a completely black background is 1.16. 

If we can guaranteee that the borders have a color contrast of at least 1.36 (equivalent of #ddd against #fff), I think that would be enough to make them visible in most cases. Is it possible to add a conditional that checks if the border colors reach that minimum contrast, and if not, adjusts them until they do?

**Comment by aristath** [comment]
> If we can guaranteee that the borders have a color contrast of at least 1.36 (equivalent of #ddd against #fff), I think that would be enough to make them visible in most cases. Is it possible to add a conditional that checks if the border colors reach that minimum contrast, and if not, adjusts them until they do?

@andersnoren done, see PR on https://github.com/WordPress/twentytwenty/pull/610
