### ISSUE TITLE
Default button color in block editor doesn't match live site

### ISSUE THREAD

**Issue by byalextran** [WordPress/twentytwenty#572]
When adding a button with default styling, the color is pink in the block editor. 

![Screen Shot 2019-09-26 at 20 35 26 PM](https://user-images.githubusercontent.com/455406/65735519-62961100-e09d-11e9-98dd-282c308cbede.png)

However, on the live site, instead of pink it uses the `Accent Color Hue` set in the Customizer. 

![Screen Shot 2019-09-26 at 20 35 37 PM](https://user-images.githubusercontent.com/455406/65735917-bc4b0b00-e09e-11e9-9887-64dde0a38223.png)

I'm not sure what the correct behavior should be.

Is the block editor styling wrong and the default color in the editor should be the color selected in Customizer? Or is the block editor styling right and the live site color wrong?

**Comment by nielslange** [comment]
@byalextran I've analysed this issue and it seems that the button styles do not reflect the `Accent Color Hue` as defined in `Customizer → Colors`.

@aristath As you've implemented https://github.com/WordPress/twentytwenty/pull/249 would you mind checking why the elected `Accent Color Hue` only seem to affect the button style `Outlined`?

---

**Steps to reproduce**

1. Head over to `Customizer → Colors`
2. Select an `Accent Color Hue` (other than red for testing purposes)
3. Heade over to `Posts → Add New`
4. Add a button block
5. Open sidebar and look up button styles

**Expected behaviour**

The button styles `Default` and `Squared` show a red background, as seen in https://github.com/WordPress/twentytwenty/issues/572#issue-499193101 and only the button style `Outlined` reflects the selected `Accent Color Hue`

**Current behaviour**

All three button styles show the selected `Accent Color Hue`

**Comment by aristath** [comment]
> @aristath As you've implemented #249 would you mind checking why the elected Accent Color Hue only seem to affect the button style Outlined?

On the frontent colors are applied using this: https://github.com/WordPress/twentytwenty/blob/739b670b5cae406b51c9a0afc2db52357508dcec/inc/custom-css.php#L95-L106

The list of elements used there comes this function: from https://github.com/WordPress/twentytwenty/blob/master/functions.php#L613-L668

For the block editor we don't have such an array and instead we're using hardcoded values here: https://github.com/WordPress/twentytwenty/blob/739b670b5cae406b51c9a0afc2db52357508dcec/inc/custom-css.php#L121-L142

Perhaps instead of these hardcoded values we should build a similar array to the one we use for the frontend, and use an implementation similar to the loop we have for the front?

**Comment by carolinan** [comment]
I feel that yes, the more similar they are, the easier it will be to maintain and make changes to.

**Comment by nielslange** [comment]
@aristath Are you able to modify the button block in a way that it picks up the select `Accent Color Hue`? Even for me as an advanced WordPress user, it's a bit hard to understand why colours seem to randomly change. And while I have a logical explanation for it, my mum would be totally lost here. 

Thus, in my opinion, and please correct me if I'm mistaken @carolinan and @andersnoren, the blocks should show the elements based on the selected `Accent Color Hue` to avoid confusion on the user's end.

**Comment by aristath** [comment]
@nielslange yes, that part is simply not complete yet. The plan is to have styles properly applied to the block editor as well.

@carolinan I believe we can get away simply by reusing the array we have for the frontend by simply prepending `.editor-styles-wrapper ` to each item?

**Comment by nielslange** [comment]
That's great to hear, @aristath!

**Comment by aristath** [comment]
I did an experiment and it kind of works... By "kind of works" I mean all styles are properly applied, however they are applied to more elements than they should.

What I did to test this:

right below this line in `custom-css.php`:
```php
} elseif ( 'block-editor' === $type ) {
```
I added this:

```php
// Auto-calculated colors.
$elements_definitions = twentytwenty_get_elements_array();
foreach ( $elements_definitions as $context => $props ) {
	foreach ( $props as $key => $definitions ) {
		foreach ( $definitions as $property => $elements ) {
			$val = twentytwenty_get_color_for_area( $context, $key );
			if ( $val ) {
				twentytwenty_generate_css( '.editor-styles-wrapper [data-block] ' . implode( ',.editor-styles-wrapper [data-block] ', $elements ), $property, $val );
			}
		}
	}
}
```
Buttons and all other elements now get the styles they should, however this was a side-effect:

![Screenshot_2019-09-28 Edit Post ‹ localhost — WordPress](https://user-images.githubusercontent.com/588688/65813266-aa22b700-e1db-11e9-8b49-520d390b3baf.png)

The color is applied to the link-selector, and also the button with the invisible text is an outline button.

I'm thinking that instead of the above code in `custom-css.php` we could add a condition in the `twentytwenty_get_elements_array` function, and if we're in the block editor tweak the array items there.

**Comment by ianbelanger79** [comment]
@aristath did this get any further? We are currently in RC and need to know what bugs we can still fix. Thanks

**Comment by carolinan** [comment]
Just adding notes here for transparancy. The suggested sollution proved too complex and will not be added in time. The current way of targeting the elements will be used.

Progress has already been made, this needs additional testing to see if it is still an issue.

**Comment by carolinan** [comment]
I have confirmed that the color works, closing the issue.
