### ISSUE TITLE
Small jump when opening the modals (menu & search) if the page if a bit scrolled

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#585]
The title is self explanatory, see the video below to see it in action. This is a small bug, but when it happens I find it a bit annoying because the scroll to top is not the expected behavior.

It wasn't happening in the theme's initial commit.

![jump](https://user-images.githubusercontent.com/54663751/65791142-668b6700-e161-11e9-9191-9bb00129d907.gif)

**Comment by carolinan** [comment]
What browser are you using? Are you logged in or not? I can't see the menu bar so I'm guessing not.

**Comment by yannickiki** [comment]
@carolinan on every browser (Chrome, Safari, Firefox) on Mac & Windows. I was logged in for the screencap with the admin bar disabled. It also happens for non logged in visitors.

**Comment by andersnoren** [comment]
Hi @yannickiki! The scroll to the top is deliberate, as it ensures that the header and menu overlap correctly on mobile and tablet, when the header and the mobile menu are visible at the same time. Without the scroll to the top, you could end up with this:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/8181091/65794667-e9fc8680-e168-11e9-9710-7a71b33c309c.png">

There could be a case made that this behavior isn't needed on desktop, though, since the header and modal menu doesn't have the same relationship there.

**Comment by acosmin** [comment]
We could probably detect if we're on a mobile device and remove the jump 👍 I can do that if you guys want it.

**Comment by yannickiki** [comment]
Hi @acosmin  As https://github.com/WordPress/twentytwenty/pull/628 has been merged, it seems that:

> The scroll to the top is deliberate, as it ensures that the header and menu overlap correctly on mobile and tablet, when the header and the mobile menu are visible at the same time. 

is not needed anymore as the header isn't visible when the menu modal is opened.

To avoid the jump, some of the code from the initial commit (where there was no jump) might be useful.

**Comment by andersnoren** [comment]
@yannickiki @acosmin Yes, as the header is obscured on all screen sizes now, the scroll to top when a modal is displayed can be removed entirely.

**Comment by acosmin** [comment]
@andersnoren I did remove the scroll to top 😄 but I had to do some change to cover template... otherwise it wouldn't work in the current setup.
