### ISSUE TITLE
Audio block styling

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentytwenty#592]
I wonder if considering a darker color to contrast with background would be good?

![image](https://user-images.githubusercontent.com/253067/65798556-d69deb00-e169-11e9-9d50-9ca9d6a32dd5.png)

**Comment by okpierre** [comment]
This is what I see on my end

![twentytwenty-audio-block-with-caption](https://user-images.githubusercontent.com/1679025/65809550-51680580-e16c-11e9-9cab-79e26693e4a4.png)

**Comment by joyously** [comment]
Which browsers and OS, for both?

**Comment by afercia** [comment]
These are just the native browsers players. Audio (and video) players are rendered differently across browsers. This also depends on the media type natively supported by each browser. Not sure they can be styled consistently (or styled at all) and not sure they _should_ be styled to start with. As far as I can tell, also the previous bundled themes don't try to style them.

Chrome:

<img width="652" alt="Screenshot 2019-09-28 at 12 21 54" src="https://user-images.githubusercontent.com/1682452/65815209-bc592100-e1ec-11e9-9f8c-48a958a31a68.png">

Firefox:

<img width="661" alt="Screenshot 2019-09-28 at 12 22 03" src="https://user-images.githubusercontent.com/1682452/65815210-bc592100-e1ec-11e9-8859-ca6758f551ca.png">

Safari:

<img width="654" alt="Screenshot 2019-09-28 at 12 22 13" src="https://user-images.githubusercontent.com/1682452/65815211-bcf1b780-e1ec-11e9-8bcf-4ae2be28c172.png">

When the media type is not supported, `mediaelement.js` should kick in and provide its JavaScript player. In the past, this happened more often because browsers support for media types was different,

**Comment by ianbelanger79** [comment]
@afercia is correct, these are native players, which can be very difficult to style, if at all. We will not be trying to style them.
