### ISSUE TITLE
Consider making reply and edit not same button type

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentytwenty#602]
Currently, the edit and reply buttons have primary styling, I would say one could just be text, as the edit link on post/page is.

![image](https://user-images.githubusercontent.com/253067/65802173-c63e3e00-e172-11e9-921c-d512569723a6.png)

**Comment by okpierre** [comment]
@karmatosed 

> I would say one could just be text, as the edit link on post/page is

are you referring to this?

current post edit link
![twentytwenty-edit-this-link](https://user-images.githubusercontent.com/1679025/65804138-de9c6180-e14e-11e9-98df-bc6d15dd4cc6.png)

**Comment by carolinan** [comment]
@okpierre The first screenshot is from the comment section, not the post edit.

It does not yet match the design:

![reply](https://user-images.githubusercontent.com/7422055/65812682-e3066000-e1ca-11e9-91d9-9ef607a95629.png)



When the colors are added to the reply, I think the accent color for the edit makes the edit to prominent, because the reply is the "primary" action here.
