### ISSUE TITLE
Inline icon label when no "Desktop Horizontal Menu" is set

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#720]
Currently when there is no "Desktop Horizontal Menu" set, the labels for the Menu and Search icons are stacked. According to the Figma mockups, the labels of Menu and Search icons should be inline with a bigger font-size.

**Before:**

![stack](https://user-images.githubusercontent.com/54663751/66050151-ef711c80-e52c-11e9-9a40-a775394fba26.jpg)

**After:**

![inline](https://user-images.githubusercontent.com/54663751/66050152-f0a24980-e52c-11e9-992b-e92d200ec623.jpg)

@andersnoren could you please confirm this? 🙂

**Comment by andersnoren** [comment]
@yannickiki Yeah, the original plan was to use that toggle layout on desktop when the "Horizontal Desktop Menu" is not set. Given that the header is already pretty complex, we decided to leave this one as a "nice-to-have" in case there's time. Since the expanded menu will only be used if opted into, and the primary menu will not be used only if opted out of, the number of users that will only have the expanded menu set is probably pretty low.

But if someone feels inclined to implement this update on > 1000px screens, it's up for grabs. 🙂 It would need to be done pretty quickly though, and preferably only with CSS changes.

**Comment by glauberm** [comment]
I'll try to work on a PR addressing this today.

**Comment by glauberm** [comment]
#723 @andersnoren I understood from what you said that I should keep the changes to a minimum, so I didn't follow the after picture styles very thoroughly, ignoring the font size and color, and only guessing the spacing between the icon and the label. Let me know if I should apply these styles.

**Comment by glauberm** [comment]
Also, working on this issue I found a missing bracket on [line 4317 of `style-rtl.css`](https://github.com/WordPress/twentytwenty/blame/a7fab672077f31bd232318ee2d3cd3cce1b8e15f/style-rtl.css#L4317). Weirdly enough, [the blamed PR](https://github.com/WordPress/twentytwenty/pull/576/files) has the bracket... Anyway, let me also know how you wanna handle this.
