### ISSUE TITLE
Dark background in editor is not readable

### ISSUE THREAD

**Issue by ryelle** [WordPress/twentytwenty#738]
I set a dark background on the content area, which looks great on the front end, but something is not working right in the editor:

<img width="730" alt="Screen Shot 2019-10-03 at 11 11 16 AM" src="https://user-images.githubusercontent.com/541093/66139552-a671a480-e5ce-11e9-9739-9bd7ea047a5d.png">

It looks like two things are happening:

- the dark theme is not being turned on because you need to [support both `dark-editor-style` and `editor-styles`.](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/admin-header.php#L198)
- the generated customizer styles that add the white text color are [being overridden by this style.](https://github.com/WordPress/twentytwenty/blob/master/assets/css/editor-style-block.css#L15)

**Comment by joyously** [comment]
I've been trying to get the dark editor style thing changed in the editor, like it's up to the editor to make its UI visible at all times, and it shouldn't be the theme's responsibility. This is a perfect example of that.
The editor UI elements should have background colors, so that the theme colors don't affect it.
But the editor team made it the theme's job to call a function for dark theme support.
Maybe we could apply more pressure to get this changed, so all themes don't have to examine the colors selected by the user just so they can call an editor function? ???
