### ISSUE TITLE
Background-link in Appearenace menu section

### ISSUE THREAD

**Issue by kebbet** [WordPress/twentytwenty#858]
After #480 the link to "Background" in the Appearance menu-section leads to a dead end. I think that the link should lead to a meaningful section in the customizer, or it should be removed from the submenu.

![image](https://user-images.githubusercontent.com/11491369/66898554-b4c1b680-eff9-11e9-8b57-7b3b4082946e.png)

**Comment by joyously** [comment]
That's not really a theme thing. It comes from the call to `add_theme_support`.

**Comment by kebbet** [comment]
I know the root of the issue is a core thing. But the User Experience right now is not the best, and I wanted to highlight that. A suggestion from me is to not use the core feature for background color, and instead add a new custom setting for the background color, and group it with the colors. In that way the link can be eliminated..

**Comment by afercia** [comment]
There's a related Trac ticket, see https://core.trac.wordpress.org/ticket/48338#comment:2

At this point of the release (WordPress 5.3 is in Release Candidate period) I'd recommend any development to happen on Trac / SVN and not on GitHub as any change must be reviewed and "signed off" by two core committers.

**Comment by afercia** [comment]
Adding details reported on https://core.trac.wordpress.org/ticket/48338

Twenty Twenty declares support for custom background. However, it handles only custom colors and doesn't provide a UI in the Customizer to handle background images.

This leads to an inconsistency in the WordPress admin UI: in the admin menu, a "Background" link is displayed:


![](http://cldup.com/tfmXSeSu02.jpg)

Clicking this link opens the Customizer but it doesn't do anything else. The customizer opens and displays its main panel in the sidebar.

Instead, the expected behavior is that it opens the Customizer ''and then'' it switches the left panel to the "Background" one. You can check what the expected behavior is by using another bundled theme that supports a background image, e.g. Twenty Sixteen:
- click on the "Background" link in the admin menu
- the Customizer opens
- after a brief delay, the "Background" panel appears sliding in from the right

Instead, with Twenty Twenty active, the Background link doesn't do what users would expect. It just opens the Customizer and... well where's the background setting?

Moreover:
it's still possible to access the legacy background page at `wp-admin/themes.php?page=custom-background` if users know the URL or if they bookmarked it. In this page I can set a background ''image'' for Twenty Twenty :) 

After that, the Customizer displays the background image:

![](http://cldup.com/UzTZYYl0ZH.jpg)

But then again, the Customizer doesn't provide any UI to manage the background image.

–––––––––––

I now see it's intentional in Twenty Twenty:

https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwenty/classes/class-twentytwenty-customize.php?rev=46551&marks=29-33#L28

`$wp_customize->remove_section( 'background_image' );`

However, this leads to a user experience that's not ideal, IMHO.

Also, at this point of the release (we're in Release Candidate) development should really happen on Trac / SVN and not on GitHub as any change must be reviewed and "signed off" by two core committers.

**Comment by ianbelanger79** [comment]
I'm not sure of the best way to handle this issue at this point. Here are the options I see:

- Hide the Background menu item completely
- Redirect the Background menu item to the Colors tab

But I'm not sure if we can do either of these during RC. Thoughts? Suggestions?

**Comment by kebbet** [comment]
Or 
- bring back background image?
- disable core backgorund color, and add custom background color option for theme?

**Comment by acosmin** [comment]
I would just hide the Background menu item in wp-admin...

**Comment by joyously** [comment]
I would put the Background Image option back in. It doesn't hurt anything and it works as expected.

**Comment by kebbet** [comment]
I agree with https://github.com/WordPress/twentytwenty/issues/480#issuecomment-534879796

Site owner could simply just not use a background image if he/she is concerned about accessibility.

Let the user take the decision, and not take it for them.

**Comment by afercia** [comment]
On #480 I read:
> We did the same for Twenty Nineteen.

If I'm not wrong that's a bit different though. Twenty Nineteen doesn't support custom-background at all so there's no issue related to the admin menu.

I'm not a Customizer expert at all but for the future maybe the best option would be to have 2 separate background support for 1) image and 2) color. Or changing the "Background Image" customizer panel to a generic "Background" one, capable to handle both color and / or image.

For now, the usability problem with the admin menu is pretty evident and personally I'd lean towards a standard way to solve it by not removing the background section.
