### ISSUE TITLE
function twentytwenty_get_post_meta is not pluggable any more

### ISSUE THREAD

**Issue by maxcady** [WordPress/twentytwenty#860]
Now it is quite complicated to change appearance of the post meta (i.e. move from single-top to single-bottom) in a child thme

**Comment by schwigri** [comment]
For reference, in [761faa7](https://github.com/WordPress/twentytwenty/commit/761faa7b4a2194f96fcaee9aff7da5868d3550e6#diff-5915276465e785d5f7897d71685fca5f), the `if ( ! function_exists( 'foo' ) ) {` blocks were removed from the functions in `inc/template-tags.php`.

Whether this should be reversed is something that should be discussed.

**Comment by joyously** [comment]
Hmmm, yes, when I submitted the original PR, it was to `remove if statements around hooks and filtered functions`, but it looks as if the "Redo" took more if statements out.

**Comment by maxcady** [comment]
the function post_meta should have an if statement. Otherwise it is not possible to move the post meta below the content in a child theme.

**Comment by andersnoren** [comment]
The `twentytwenty_get_post_meta` function includes two filters for the two different post meta locations:

```
twentytwenty_post_meta_location_single_top
twentytwenty_post_meta_location_single_bottom
```

So you can use filters to change which post meta is displayed in which location – you don't need to plug the entire function for that.

**Comment by itsViney** [comment]
This issue is causing problems for me also. I need to insert a custom piece of metadata the post date and the categories and in twenty-nineteen I did this by redeclaring twentynineteen_posted_on in the child theme. I'm not able to do this in twentytwenty because I can't re-declare twentytwenty_get_post_meta.

Perhaps it might also me a good idea to break twentytwenty_get_post_meta into smaller functions so that the entire thing doesn't have to be redeclared.

**Comment by Aetles** [comment]
Is there any good reason _not_ to have the function wrapped with `function_exists`?
