### ISSUE TITLE
The "To the top" scrolls to the wrong place in the cover template

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#885]
If you view a cover template _and press the arrow in the header that scrolls down to the content_,
it seems the height is not calculated correctly if you then click on the "To the top" link because
it only takes you to the top of the content, not to the top of the page.

**Comment by joyously** [comment]
I think it's not just when jumping down and then up. It's always, when using the cover template, because the `#site-header` overlaps the `#site-content`.

Is it correct to assume that the page title is part of the content? Or should it just be the entry content that is the target?

Also, the "to the top" link can use `#` which will always go to the top, without needing any specific target to be in the page.

**Comment by carolinan** [comment]
Personally I would expect it to go all the way to the top and that the next focusable item would be the first skip link.
