### ISSUE TITLE
Customizer: color settings for primary color don't work

### ISSUE THREAD

**Issue by maxcady** [WordPress/twentytwenty#914]
The color settings for primary color in customizer don't work everywhere (links or buttons). The color of links won't change (the link color changes in the widget area only). And there should be a field for color hexcode (like the color picker for background color). The color slider alone doesn't allow to set a specific color as primary color. If I know the hexcode of the color I don't have the option to set this specific color in customizer. It would be better to have a color picker than a color slider. The color slider is very imprecise.

**Comment by joyously** [comment]
I think this is worthy of consideration, just because of the name of the option and the way most people would want to customize the site.
If the user could set the primary color with a standard color option, and the background colors were auto-generated, that would get more users their desired design. 
Could the color generation be flipped like that?
Or rename Primary to something else.

**Comment by ianbelanger79** [comment]
At this point, we cannot rework the complete color picking system, marking for `Future Consideration`
